input_file: C:\Users\sayye\.cache\kagglehub\datasets\sakshisatre\tips-dataset\versions\3\tip.csv
output_dir: output/tips
report_title: EDA on tips dataset
target_variable: tip
analysis_pipeline:
- profile:
    enabled: true
- univariate:
    enabled: true
    plot_types:
      numerical:
      - histogram
      - boxplot
      categorical:
      - barplot
- bivariate:
    enabled: true
    target_centric: true
- multivariate:
    enabled: true
    correlation_cols: []
